In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import ast

In [2]:
df = pd.read_csv('/Users/jchang153/Documents/UCLA-CAM/GV KG/Data/Tweets/All/bigbabies/bigbaby_r_t_30_s.csv')

### Exploring probabilities

In [4]:
df.columns[:35]

Index(['created_at', 'tweet_id', 'text', 'in_reply_to_tweet_id',
       'in_reply_to_user_id', 'geo', 'quote_count', 'reply_count',
       'retweet_count', 'favorite_count', 'lang', 'quoted_tweet_id',
       'possibly_sensitive', 'user_id', 'screen_name', 'followers_count',
       'friends_count', 'statuses_count', 'verified', 'hashtags', 'mentions',
       'date', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
       '12'],
      dtype='object')

In [3]:
L = [str(i) for i in range(270)]

In [4]:
probs = df[L].values

In [5]:
probs[5]

array([2.79792086e-04, 4.42257598e-04, 3.40209202e-04, 9.01878303e-04,
       3.75397588e-04, 4.83937747e-03, 9.21027140e-04, 4.14794498e-04,
       1.15912930e-04, 5.58123963e-04, 3.05304077e-04, 6.07598754e-04,
       5.26994003e-04, 5.25166222e-04, 5.53364587e-04, 8.54068130e-05,
       1.59292215e-04, 3.78922471e-04, 3.06753086e-04, 2.81616412e-04,
       6.28440119e-04, 5.08225308e-04, 3.52389670e-04, 2.51728528e-04,
       2.72288567e-04, 3.27161541e-04, 9.97820916e-04, 4.23876086e-04,
       3.58581047e-04, 6.75011817e-04, 2.82462493e-04, 1.20731980e-04,
       3.58065214e-04, 3.91435128e-04, 4.57009138e-04, 2.43036553e-04,
       7.88592761e-05, 3.35836338e-04, 8.66787547e-04, 2.20051132e-04,
       4.66604324e-04, 4.53702901e-04, 7.97646330e-04, 5.75003049e-04,
       2.90185599e-04, 1.27640726e-03, 4.26617016e-04, 1.46126122e-03,
       9.85937172e-04, 5.60625294e-04, 3.15787273e-04, 3.20213294e-04,
       3.32581760e-04, 3.46733100e-04, 2.97556461e-04, 3.05567258e-04,
      

In [6]:
len(df['user_id'].unique()), len(df)

(26141, 74639)

In [9]:
probs >= .01

array([[ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False,  True],
       [False, False, False, ..., False, False, False]])

In [10]:
# for each tweet, count the number of topics for which 
# it has greater than .01 probability of being in.
l=[]
l2 = []
for i in np.sum(probs >= 0.01, axis=1):
    # print(i)
    l.append(i)
    if i != 0:
        l2.append(i)

In [8]:
np.mean(l)

3.4383097308377657

In [11]:
np.mean(l2)

3.9545118343195265

In [12]:
np.max(l)

23

In [18]:
for i in df[df['topics'] == 27]['text'][:50]:
    print(i)

ahmaudarbery blacklivesmatter justiceforahmaud https://t.co/u9zgybipsr
justice for george georgefloyd blacklivesmatter https://t.co/gslugdjxq9
🙏🏽 thisisamerica thereal allwehaveisnow georgefloyd standup alllivesmatter blacklivesmatter justice… https://t.co/ewoff5ux83
justiceforgeorgefloyd blacklivesmatter https://t.co/gwambthvcb
its as easy as this blacklivesmatter 

text “floyd” to 55156

text “justice” to 668366 https://t.co/tueljucvwu
this...  blacklivesmatter justiceforfloyd justiceforahmaud wearetired ijustwannalive @ noho arts district https://t.co/fbfjohte27
if you see this and don’t support, unfollow me justiceforgeorgefloyd icantbreathe blacklivesmatter https://t.co/rus5c1zj6z
@joynerlucas tully @iprevailband absolute masterpiece. justiceforgeorgefloyd icantbreathe https://t.co/ywcigtkbzb
justiceforgeorgefloyd blacklivesmatters https://t.co/rl7x3qgakf
https://t.co/9f0racmtvr blacklivesmatter justiceforgeorgefloyd
a message from our ceo here at buddyjane 

ripgeorgefloyd justic

In [85]:
for i in df[df['topics'] == 268]['text']:
    print(i)

“you’re not to be so blind with patriotism that you can't face reality. wrong is wrong, no matter who does it or says it.” georgefloyd
this isn’t about race, this is about the people versus the powers that be. it is about us versus the unchecked. georgefloyd
georgefloyd icantbreathe nojusticenopeace https://t.co/1nrj7en9nr
keeping it real.

georgefloyd 
nojusticenopeace
the power of the people is strong. the spirit of georgefloyd is with us.  this is the beginning of the revolution.
just some relatable expression in these agitating times ✊🏽 georgefloyd icantbreathe nojusticenopeace https://t.co/osuobkzk7t
nojusticenopeace georgefloyd ahmaudaubrey breannataylor https://t.co/szqpcstbsu
appreciate the kind remark.  let’s unite to bring real change in honor of georgefloyd 🙏. additional federal civil… https://t.co/bjzwdc9scr
the feelings out here are abundantly clear! truth nojusticenopeace stopkillingus georgefloyd beverlyandfairfax… https://t.co/9toxjpgnml
georgefloyd brought us together.

In [ ]:
np.sort(np.max(probs, axis=1))[:10000]

array([1.89570915e-07, 1.89571112e-07, 1.89572162e-07, ...,
       1.03333741e-02, 1.03351063e-02, 1.03353344e-02])

In [ ]:
probs[0]

array([0.04161207, 0.00164122, 0.00193225, 0.00223813, 0.00173183,
       0.00265605, 0.00397404, 0.0013724 , 0.00087461, 0.00179977,
       0.00626951, 0.00195445, 0.0016906 , 0.00173549, 0.00188698,
       0.0006194 , 0.001538  , 0.00182612, 0.00159731, 0.00216144,
       0.0019719 , 0.00161577, 0.00154588, 0.00125445, 0.01207483,
       0.00160786, 0.00199592, 0.00153946, 0.00167443, 0.00235126,
       0.01829171, 0.00143029, 0.00168225, 0.00154015, 0.00188441,
       0.00241831, 0.00061896, 0.01980138, 0.00191919, 0.00133256,
       0.00140405, 0.00165945, 0.0021173 , 0.00166882, 0.00188088,
       0.00195895, 0.00172922, 0.0022467 , 0.00293573, 0.00157476,
       0.00161643, 0.0015403 , 0.00148738, 0.0017115 , 0.00129372,
       0.03159811, 0.00284411, 0.00185208, 0.00196543, 0.0052479 ,
       0.00455884, 0.0030774 , 0.0016944 , 0.00136822, 0.00118787,
       0.00261699, 0.00149993, 0.00161975, 0.00190413, 0.00163297,
       0.00182716, 0.00178672, 0.01377261, 0.00160519, 0.00134

In [ ]:
np.argmax(probs[0])

0

In [ ]:
probs.shape

(74639, 270)

In [ ]:
topic_idx = 28  # Topic index is 0-based, so topic 28 corresponds to index 27

# Get the probabilities for topic 28 for all tweets
prob_topic_28 = probs[:, topic_idx]

# Use numpy.where() to find the indices of tweets that meet the condition
indices = np.where(prob_topic_28 >= 0.01)[0]

In [ ]:
indices

array([   11,    90,   104,   105,   259,   377,   464,   503,   536,
         699,   702,   704,   840,  1064,  1197,  1250,  1262,  1278,
        1285,  1308,  1338,  1422,  1424,  1497,  1586,  1604,  1653,
        1660,  1725,  1784,  1786,  1858,  1861,  1863,  1864,  1915,
        2059,  2066,  2070,  2098,  2103,  2105,  2122,  2148,  2226,
        2254,  2357,  2360,  2424,  2637,  2654,  2736,  2763,  2865,
        2869,  2918,  2947,  2978,  3023,  3036,  3055,  3118,  3194,
        3243,  3335,  3420,  3494,  3556,  3557,  3564,  3569,  3576,
        3582,  3651,  4053,  4056,  4069,  4072,  4125,  4191,  4222,
        4286,  4288,  4310,  4315,  4359,  4438,  4469,  4510,  4554,
        4564,  4572,  4591,  4596,  4635,  4717,  4718,  4725,  4733,
        4742,  4808,  4809,  4857,  4876,  4895,  5134,  5247,  5254,
        5258,  5299,  5505,  5623,  5768,  6276,  6566,  6963,  7392,
        8143,  8270,  9426, 10330, 12277, 12870, 12961, 13101, 13129,
       13672, 13714,

In [80]:
df.iloc[74593]

'some of the world’s dumbest people are the ones who think homophobia means you’re afraid of gay people.'

In [ ]:
np.argsort(probs[20])

array([ 36,  75,  96,  15, 204, 119,  31, 161, 120, 234, 103, 241,   8,
       195,  16, 201,  99, 220, 239, 248, 243,  39, 237, 108, 186, 143,
         4,  71, 242,  35, 136, 150,  46, 199,  65, 251, 264,  34, 124,
        64,  88, 121,   0,  30, 230,  87,  54, 218,  68,  74, 207, 139,
       129,  91,  52, 246, 154, 205,  24,  80, 240,  55,  82,  72, 169,
        73, 158, 134, 253,  37, 224, 197,  93,  27, 178, 175, 127, 100,
       113,  83,  50,  76, 179,  98, 212,  20,  60, 233, 260,  79, 114,
       206,  92, 216, 208,  95, 214, 152, 140, 268, 160,   9, 191, 155,
        51,  25, 118, 256, 188, 221, 219,  41,  10, 200, 257, 157,  11,
        23,   1,  33, 105, 202, 210,  62, 235,   6, 190, 131,   3, 137,
       112, 249, 146, 259, 123, 173, 266,  48,   7,  59, 164,  86, 144,
       193, 231, 236, 163,  81, 261,  61, 128, 148, 244,  42, 168,  78,
       211, 192, 181, 176,  66, 250,  63, 194,  56, 165, 117, 258,  94,
        40, 106, 167, 156,  85, 153, 185, 102, 184, 122, 132, 23

In [ ]:
df.iloc[20]

created_at                                            2020-03-11 19:07:29
tweet_id                                            1237817438311305216.0
text                    @digitalchicana transphobia and racism is taug...
in_reply_to_tweet_id                                1237817017551523840.0
in_reply_to_user_id                                 1162368928754077696.0
                                              ...                        
266                                                              0.000748
267                                                              0.001177
268                                                              0.000649
269                                                              0.001154
topics                                                                 53
Name: 20, Length: 293, dtype: object

### Picking relevant topics

In [19]:
doc_info = pd.read_csv('/Users/jchang153/Documents/UCLA-CAM/GV KG/Data/Tweets/All/topics/bigbaby_r_30_docs.csv')
top_info = pd.read_csv('/Users/jchang153/Documents/UCLA-CAM/GV KG/Data/Tweets/All/topics/bigbaby_r_30_tops.csv')

In [4]:
black_topics = [1,2,3,4,7,8,9,11,13,15,19,20,21,23,25,27,31,34,36,38,40,41,42,44,45,46,47,48,50,
51,52,56,62,63,64,66,68,70,71,73,75,76,78,82,83,84,86,88,92,93,94,101,102,105,106,
107,109,111,114,117,119,120, 121,122,123,124,125,126,131,132,133,137,140,143,144,145,
146,147,149,150,151,153,154,155,157,160,162,163,164,165,166,168,169,171,172,177,
178,179,180,184,186,187,188,191,193,196,200,202,203,206,208,211,212,216,218,220,222,
223,224,225,226,228,229,230,233,235,242,244,245,250,251,253,254,255,256,259,260,261,266,
268,269]

lgbt_topics = [28,26,58,175,57,209,22,53,168,180,18,156,182,104,215,247]

# racism_topics = [13, 91, 105, 117, 119, 192, 121, 91, 122, 126, 225,244]
jewish_topics = [79,24,72,0,30,37,55,87,91,129,121,129,199,205,264,10,59,5,6,100,262]
asian_topics = [67,69,96,115,135,147,161,16,99,183,195,201,221,243,101]
hispanic_topics = [32,35,65,135,142]

In [7]:
len(black_topics), len(asian_topics), len(lgbt_topics)

(141, 15, 16)

In [5]:
top_list = black_topics + asian_topics+lgbt_topics

In [15]:
df2 = df[df[[str(num) for num in top_list]].ge(0.01).any(axis=1)]
len(df2)/len(df)

0.689867227588794

In [16]:
len(df2)

51491

In [43]:
for i in df[df['topics'] == 85]['text']:
    print(i, '\n')

@boobalander and happy birthday mine was last saturday .
first day of quarantine ,didn’t even got the cake this year 🤣 chinesevirus 

happy birthday to you @speakerpelosi 
please continue to make orange hitlers life difficult and miserable until jan… https://t.co/uuuajqjcti 

hitlers birthday, columbine school shooting and 420 

rip ahmaudarbery happy birthday 🙏🏽 

irunwithmaud 🏃🏾‍♀️🏃🏿happy birthday to ahmaudarbery who was shot and killed for exercising while being black😔as a… https://t.co/gviwltibym 

@andrew_lopeeezz @jakeskytte happy birthday faggot https://t.co/rkmjasten6 

kike hernandez cupcake toppers 🧁🎂🎉💙⚾️🧢 happy 13th birthday to my former student lizbeth 👧🏻 dodgerlove… https://t.co/aoj0j1eexx 

happy birthday fag https://t.co/th9h1q7l57 

@iivaness_ beaners day 

rest well 
breonnataylor ahmaudarbery georgefloyd 

thank you for sharing your gift keedronbryant @ unknown https://t.co/lagvlgulxz 

respect fellow gemini ♊️ @ayeemalik99 happy belated birthday. blacklivesmater geor

In [45]:
for i in top_info[top_info['Topic'].isin(jewish_topics)]['Name']:
    print(i)

0_nazi_nazis_the nazis_the nazi
5_hitler_he_his_him
6_trump_hitler_trump is_trump supporters
10_anti_semitic_anti semitic_semitism
24_holocaust_the holocaust_survivor_holocaust survivor
30_germany_nazi germany_nazi_german
37_trump_nazi_nazi trump_trump is
55_he_nazi_him_he is
59_antisemitism_antisemitic_antisemitism is_the antisemitism
72_she_her_nazi_the holocaust
79_jews_jewish_holocaust_the holocaust
87_nazi_nazi officers_rso_joebiden
91_white_nazis_nazi_racist
100_stalin_putin_hitler_russia
121_flag_flags_nazi flag_confederate
129_republican_party_republican party_nazi
199_symbol_cpac_nazi symbol_nazi
205_bernie_nazi coup_coup_bernie is
262_hitler youth_youth_hitler_the hitler youth
264_nazi rally_rally_1939_madison square


In [6]:
top_set = {1,2,3,4,7,8,9,11,13,15,19,20,21,23,25,27,31,34,36,38,40,41,42,44,45,46,47,48,50,\
 51,52,56,62,63,64,66,68,70,71,73,75,76,78,82,83,84,86,88,92,93,94,101,102,105,106,\
 107,109,111,114,117,119,120, 121,122,123,124,125,126,131,132,133,137,140,143,144,145,\
 146,147,149,150,151,153,154,155,157,160,162,163,164,165,166,168,169,171,172,177,\
 178,179,180,184,186,187,188,191,193,196,200,202,203,206,208,211,212,216,218,220,222,\
 223,224,225,226,228,229,230,233,235,242,244,245,250,251,253,254,255,256,259,260,261,266,\
 268,269,28,26,58,175,57,209,22,53,168,180,18,156,182,104,215,247,13, 91, 105, 117, 119, \
 192, 121, 91, 122, 126, 225,244,79,24,72,0,30,37,55,87,91,129,121,129,199,205,264,10,59,\
 5,6,100,262,67,69,96,115,135,147,161,16,99,183,195,201,221,243,101,\
 32,35,65,135,142}

In [7]:
len(top_set)

192

In [8]:
top_to_name = top_info.set_index('Topic')['Name'].to_dict()

In [9]:
tweet_dict = df.to_dict(orient='records')

In [10]:
all_relations=[]

In [11]:
tweet_topic_relations = []
for tweet in tqdm(tweet_dict):
    for i in top_set:
        if tweet[f'{i}'] >= 0.01:
            relation = []
            relation.append((tweet['tweet_id'], 't'))
            relation.append(top_to_name[i])
            relation.append(tweet[f'{i}'])
            relation.append(tweet['date'])
            
            tweet_topic_relations.append(relation)

all_relations = [*all_relations, *tweet_topic_relations]

100%|██████████████████████████████████| 74639/74639 [00:02<00:00, 27585.79it/s]


In [12]:
all_relations_df = pd.DataFrame(all_relations, columns=['tweet', 'topic', 'weight', 'date'])
all_relations_df.to_csv('./data/tweet-topic-triples.csv', index=False)

In [13]:
all_relations_df

tweet  \
0       (1.2376379784002478e+18, t)   
1       (1.2376379784002478e+18, t)   
2       (1.2376379784002478e+18, t)   
3       (1.2376379784002478e+18, t)   
4       (1.2376379784002478e+18, t)   
...                             ...   
215617  (1.4054090950503588e+18, t)   
215618  (1.4054090950503588e+18, t)   
215619  (1.4054090950503588e+18, t)   
215620  (1.4054090950503588e+18, t)   
215621  (1.4054192059445043e+18, t)   

                                                    topic    weight  \
0                         0_nazi_nazis_the nazis_the nazi  0.041612   
1       24_holocaust_the holocaust_survivor_holocaust ...  0.012075   
2                     30_germany_nazi germany_nazi_german  0.018292   
3                       37_trump_nazi_nazi trump_trump is  0.019801   
4                                    55_he_nazi_him_he is  0.031598   
...                                                   ...       ...   
215617     187_patrols_slave patrols_slave_slave catchers  0.012649   
215618                       203_he_slaves_his slaves_his  0.026358   
215619                       245_slaves_her_she_harris is  0.038493   
215620            269_slaves_slave_the slave_of the slave  0.037419   
215621                    22_drag_drag queen_queen_queens  0.024349   

              date  
0       2020-03-11  
1       2020-03-11  
2       2020-03-11  
3       2020-03-11  
4       2020-03-11  
...            ...  
215617  2021-06-17  
215618  2021-06-17  
215619  2021-06-17  
215620  2021-06-17  
215621  2021-06-17  

[215622 rows x 4 columns]

### Analyzing graph

In [72]:
import networkx as nx

In [83]:
graph = nx.Graph()

# Add edges from the DataFrame
for _, row in all_relations_df.iterrows():
    graph.add_edge(row['tweet'], row['topic'], weight=row['weight'])

In [87]:
nx.is_connected(graph)

False

In [88]:
import networkx as nx
import community  # python-louvain library

# Apply the Louvain algorithm to detect communities
partition = community.best_partition(graph)

# Print the number of communities and the mapping of nodes to communities
print("Number of communities:", len(set(partition.values())))
print("Node-community mapping:", partition)

Number of communities: 70
Node-community mapping: {(1.2376379784002478e+18, 't'): 0, 0: 0, 24: 0, 30: 0, 37: 0, 55: 0, 72: 0, 87: 0, 91: 0, 100: 0, 121: 0, 129: 0, 199: 0, 264: 0, (1.2377216448413082e+18, 't'): 1, 65: 1, (1.2377216883907748e+18, 't'): 1, 35: 1, (1.23772447892838e+18, 't'): 2, 2: 2, 44: 2, 107: 2, 172: 2, 183: 2, 187: 2, 203: 2, 245: 2, 269: 2, (1.2377251654730342e+18, 't'): 0, (1.2377585317904876e+18, 't'): 3, 5: 3, 262: 3, (1.2377617036574065e+18, 't'): 3, 196: 3, 223: 3, (1.2377676362235863e+18, 't'): 3, (1.2377701440358564e+18, 't'): 5, 18: 5, 28: 5, 53: 5, 180: 5, 209: 6, (1.237776970739409e+18, 't'): 2, (1.2377916116707287e+18, 't'): 2, (1.237796600673702e+18, 't'): 6, 22: 6, (1.2378086455611433e+18, 't'): 7, 146: 7, 266: 7, (1.2378087598098268e+18, 't'): 2, (1.237809589074051e+18, 't'): 8, 13: 8, 21: 8, 106: 8, 117: 8, 126: 8, 225: 8, 229: 8, (1.2378167105995653e+18, 't'): 2, (1.2378174383113052e+18, 't'): 5, (1.2378194785298514e+18, 't'): 9, 26: 9, 38: 9, 57: 9,

In [89]:
import networkx as nx
import community
import matplotlib.pyplot as plt

# Apply the Louvain algorithm to detect communities
partition = community.best_partition(graph)

# Create a dictionary to store node colors based on community
node_colors = {node: partition[node] for node in graph.nodes()}

# Create a list of colors to use for the plot
colors = ['red', 'blue', 'green', 'orange', 'purple', 'yellow', 'cyan', 'magenta']

# Create the plot
plt.figure(figsize=(10, 6))
pos = nx.spring_layout(graph, seed=42)  # Choose a layout for the nodes
for community_id in set(partition.values()):
    nodes_in_community = [node for node, comm_id in partition.items() if comm_id == community_id]
    nx.draw_networkx_nodes(graph, pos, nodelist=nodes_in_community, node_color=colors[community_id], label=f"Community {community_id}")

nx.draw_networkx_edges(graph, pos, alpha=0.5)
nx.draw_networkx_labels(graph, pos, font_size=8)
plt.legend(loc='upper right')
plt.axis('off')
plt.title("Communities in the Graph")
plt.show()


KeyboardInterrupt: 

<Figure size 1000x600 with 0 Axes>

### Adjacency Matrix

In [2]:
import pandas as pd
import numpy as np

In [3]:
all_relations_df = pd.read_csv('./data/tweet-topic-triples.csv')

In [4]:
from scipy.sparse import csr_matrix

In [5]:
# Create a pivot table to build the adjacency matrix
A = pd.pivot_table(all_relations_df, values='weight', index='tweet', columns='topic', fill_value=0)

In [6]:
# Convert the pivot table to a sparse matrix for efficient storage and operations
adjacency_sparse = csr_matrix(A.values)

In [18]:
# If you need to access the topics and tweet IDs separately, you can do:
tweet_ids = adjacency_matrix.index.tolist()
topic_ids = adjacency_matrix.columns.tolist()

NameError: name 'adjacency_matrix' is not defined

In [7]:
A.shape

(57199, 192)

In [8]:
A.T@A

topic                                               0_nazi_nazis_the nazis_the nazi  \
topic                                                                                 
0_nazi_nazis_the nazis_the nazi                                          162.452202   
100_stalin_putin_hitler_russia                                             4.358891   
101_blm blm_blm_paki_blm breonnataylor                                     0.000000   
102_reparations_reparations for black_reparatio...                         0.000000   
104_femboy_sissy_crossdresser_tranny                                       0.000000   
...                                                                             ...   
93_sayhername_justice for breonnataylor_justice...                         0.000000   
94_breonna_breonna taylor_taylor_taylor breonna...                         0.000000   
96_stopasianhate stopasianhate_stopasianhate st...                         0.000000   
99_virus_china_china virus_trump                                           0.000000   
9_protest_blacklivesmatter_peaceful_blacklivesm...                         0.000000   

topic                                               100_stalin_putin_hitler_russia  \
topic                                                                                
0_nazi_nazis_the nazis_the nazi                                           4.358891   
100_stalin_putin_hitler_russia                                           35.571753   
101_blm blm_blm_paki_blm breonnataylor                                    0.000000   
102_reparations_reparations for black_reparatio...                        0.000000   
104_femboy_sissy_crossdresser_tranny                                      0.000000   
...                                                                            ...   
93_sayhername_justice for breonnataylor_justice...                        0.000000   
94_breonna_breonna taylor_taylor_taylor breonna...                        0.000000   
96_stopasianhate stopasianhate_stopasianhate st...                        0.000000   
99_virus_china_china virus_trump                                          0.000000   
9_protest_blacklivesmatter_peaceful_blacklivesm...                        0.000000   

topic                                               101_blm blm_blm_paki_blm breonnataylor  \
topic                                                                                        
0_nazi_nazis_the nazis_the nazi                                                   0.000000   
100_stalin_putin_hitler_russia                                                    0.000000   
101_blm blm_blm_paki_blm breonnataylor                                           31.904564   
102_reparations_reparations for black_reparatio...                                0.000000   
104_femboy_sissy_crossdresser_tranny                                              0.008288   
...                                                                                    ...   
93_sayhername_justice for breonnataylor_justice...                                0.000000   
94_breonna_breonna taylor_taylor_taylor breonna...                                0.000000   
96_stopasianhate stopasianhate_stopasianhate st...                                0.000000   
99_virus_china_china virus_trump                                                  0.000000   
9_protest_blacklivesmatter_peaceful_blacklivesm...                                0.000000   

topic                                               102_reparations_reparations for black_reparations for_black  \
topic                                                                                                             
0_nazi_nazis_the nazis_the nazi                                                              0.000000             
100_stalin_putin_hitler_russia                                                               0.000000             
101_blm blm_blm_paki_blm breonnataylor                            

In [ ]:
tweet_space = A@A.T

In [ ]:
tweet_space.shape

### Choosing some tweets

In [24]:
top_info['Representation'] = top_info['Representation'].apply(ast.literal_eval)

In [25]:
top_info.columns

Index(['Topic', 'Count', 'Name', 'Representation', 'Representative_Docs'], dtype='object')

In [26]:
top2name = top_info.set_index('Topic')['Name'].to_dict()

In [28]:
tweet_dict = df.to_dict(orient='records')

In [31]:
df.iloc[0]

created_at                                            2020-03-11 07:14:22
tweet_id                                            1237637978400247808.0
text                    @joycewhitevance stfu you lying fascist nazi t...
in_reply_to_tweet_id                                1237467142871810048.0
in_reply_to_user_id                                           548384458.0
                                              ...                        
266                                                               0.00139
267                                                              0.001834
268                                                              0.001973
269                                                              0.001993
topics                                                                 -1
Name: 0, Length: 293, dtype: object

In [134]:
n=2090

In [136]:
for num in [81, 118, 1000, 8001, 8004, 2013, 2050, 2066, 2098]:
    print(f'Num: {num}')
    tweet = df.iloc[num]
    for i, prob in enumerate(probs[num]):
        if prob >= .01:
            print(f'%2f' % prob, top2name[i])
    print(f"\nSentiment: {tweet['sent']}\nText: {tweet['text']}\n\n\n")

Num: 81
0.024491 16_virus_china_china virus_chinese
0.040837 99_virus_china_china virus_trump
0.017512 108_coronavirus_corona_the coronavirus_covid19
0.031207 195_virus_he_chinese virus_chinese
0.053869 201_virus_calling it_racist_chinese
0.024209 243_coronavirus_chinesevirus_chinavirus_covid_19

Sentiment: 0.0
Text: this virus really putting y’all’s xenophobia out there!



Num: 118
0.907659 135_xenophobia_xenophobia is_the xenophobia_of xenophobia

Sentiment: 0.0
Text: xenophobia is not the answer. practice frequent handwashing and social distancing instead.



Num: 1000
0.483331 16_virus_china_china virus_chinese
0.027034 99_virus_china_china virus_trump
0.011627 108_coronavirus_corona_the coronavirus_covid19
0.037895 195_virus_he_chinese virus_chinese
0.035324 201_virus_calling it_racist_chinese
0.031471 243_coronavirus_chinesevirus_chinavirus_covid_19

Sentiment: 0.3612
Text: for once i agree and we shouldn’t call it the chinese virus



Num: 8001
0.025600 176_stand_stand with you

In [137]:
df_all = pd.read_csv('/Users/jchang153/Documents/UCLA-CAM/GV KG/Data/Tweets/All/bigbabies/bigbaby.csv')

/var/folders/qj/xk2kpqqd6cqb4q976yfqswf00000gn/T/ipykernel_7453/2530741199.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all = pd.read_csv('/Users/jchang153/Documents/UCLA-CAM/GV KG/Data/Tweets/All/bigbabies/bigbaby.csv')


In [140]:
df_all[df_all['text'].str.contains('for once i agree and we shouldn', case=False)]

created_at      tweet_id  \
1207630  2020-03-23 21:35:55  1.242203e+18   

                                                      text  \
1207630  For once I agree and we shouldn’t call it the ...   

         in_reply_to_tweet_id  in_reply_to_user_id  geo  quote_count  \
1207630                   NaN                  NaN  NaN          0.0   

         reply_count  retweet_count  favorite_count  ... possibly_sensitive  \
1207630          0.0            0.0             0.0  ...                NaN   

              user_id    screen_name  followers_count friends_count  \
1207630  1.218262e+18  Cocoontheleft            344.0         230.0   

         statuses_count  verified  hashtags mentions        date  
1207630          4649.0     False        []       []  2020-03-23  

[1 rows x 22 columns]

In [ ]:
2098: 2980755
8004: 6714045
1000: 1207630

In [143]:
for i in df_all.iloc[[2980755, 6714045, 1207630]]['text']:
    print(i)

homophobia is crAzy dude,’ someone get riD oF IT plz 🥺
DEREK CHAUVIN HAS BEEN ARRESTED! BUT THAT DOESN’T MEAN THIS IS OVER.
For once I agree and we shouldn’t call it the Chinese virus
